/*Generated by WaveMaker Studio*/

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

@TypeDefs({@TypeDef(name = "DateTime",
                     defaultForType = org.joda.time.LocalDateTime.class,
                     typeClass = com.wavemaker.commons.data.type.WMPersistentLocalDateTime.class)})
package com.hrdb;

import org.hibernate.annotations.TypeDefs;
import org.hibernate.annotations.TypeDef;

